//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedAssist.TelegramBot.Worker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedAssist.TelegramBot.Worker.Resources.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласен.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аллергии.
        /// </summary>
        internal static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теперь вы можете задавать вопросы..
        /// </summary>
        internal static string ChatReady {
            get {
                return ResourceManager.GetString("ChatReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хронические заболевания.
        /// </summary>
        internal static string Chronic {
            get {
                return ResourceManager.GetString("Chronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полную карточку пациента вы можете заполнить в mini app {0}..
        /// </summary>
        internal static string ClientProfileHelp {
            get {
                return ResourceManager.GetString("ClientProfileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить регистрацию.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши данные были удалены с сервера..
        /// </summary>
        internal static string DeleteUserCompleted {
            get {
                return ResourceManager.GetString("DeleteUserCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление регистрации приведет к полному удалению данных..
        /// </summary>
        internal static string DeleteUserWarning {
            get {
                return ResourceManager.GetString("DeleteUserWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти.
        /// </summary>
        internal static string GoLink {
            get {
                return ResourceManager.GetString("GoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описательное имя пациента.
        /// </summary>
        internal static string InputPatientNamePlaceholder {
            get {
                return ResourceManager.GetString("InputPatientNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть MiniApp.
        /// </summary>
        internal static string OpenMiniApp {
            get {
                return ResourceManager.GetString("OpenMiniApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пациент.
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить сессию.
        /// </summary>
        internal static string Patient_ResetSession {
            get {
                return ResourceManager.GetString("Patient_ResetSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний чат пациента восстановлен. Пациент: {0}..
        /// </summary>
        internal static string Patient_Restored {
            get {
                return ResourceManager.GetString("Patient_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сессия клиента завершена..
        /// </summary>
        internal static string Patient_SessionCompleted {
            get {
                return ResourceManager.GetString("Patient_SessionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать сессию.
        /// </summary>
        internal static string Patient_StartSession {
            get {
                return ResourceManager.GetString("Patient_StartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент {0} успешно создан..
        /// </summary>
        internal static string PatientCreated {
            get {
                return ResourceManager.GetString("PatientCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиент {0} был удален..
        /// </summary>
        internal static string PatientDeleted {
            get {
                return ResourceManager.GetString("PatientDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список ранее сохраненных пациентов. Выберете пациента, чтобы посмотреть детали..
        /// </summary>
        internal static string PatientList {
            get {
                return ResourceManager.GetString("PatientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пациенты.
        /// </summary>
        internal static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дальнейшей разговор будет происходить с учетом клиента {0} и его прошлых запросов..
        /// </summary>
        internal static string PatientSeleted {
            get {
                return ResourceManager.GetString("PatientSeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка диалога. Проверьте баланс токенов..
        /// </summary>
        internal static string PaymentRequired {
            get {
                return ResourceManager.GetString("PaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить регистрацию.
        /// </summary>
        internal static string Registration_Delete {
            get {
                return ResourceManager.GetString("Registration_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропустить.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специализация.
        /// </summary>
        internal static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специализация {0} уточнена!.
        /// </summary>
        internal static string SpecialitySelected {
            get {
                return ResourceManager.GetString("SpecialitySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для правильного подбора рекомендаций выберете специализацию..
        /// </summary>
        internal static string SpecialitySelectInvite {
            get {
                return ResourceManager.GetString("SpecialitySelectInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основное меню.
        /// </summary>
        internal static string StartMenu {
            get {
                return ResourceManager.GetString("StartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидается ответ сервиса.
        /// </summary>
        internal static string WaitingForReply {
            get {
                return ResourceManager.GetString("WaitingForReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствую, {0}! Добро пожаловать в медицинский бот-помощник. Для продолжения работы нужно подтвердить условия использования и указать специализацию..
        /// </summary>
        internal static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
    }
}
